/**
 * Data Adapters
 * 
 * Convert between new context data formats and old component formats.
 * This allows us to use the new Supabase-based contexts while keeping
 * existing components working without modification.
 */

import { Member as ContextMember } from '../contexts/MemberContext';
import { ExpenseWithSplits } from '../contexts/ExpenseContext';
import { Member as OldMember, Expense as OldExpense } from '../types';

/**
 * Convert context Member to old Member format
 */
export function adaptMember(contextMember: ContextMember): OldMember {
    return {
        id: contextMember.id,
        name: contextMember.name,
        avatarColor: undefined, // Will be generated by getMemberAvatarColor util
        user_id: contextMember.user_id, // Include user_id for identifying current user
    };
}

/**
 * Convert context Expense (with splits) to old Expense format
 */
export function adaptExpense(contextExpense: ExpenseWithSplits): OldExpense {
    return {
        id: contextExpense.id,
        description: contextExpense.description,
        amount: contextExpense.amount,
        currency: contextExpense.currency,
        paidBy: contextExpense.paid_by,
        splitBetween: contextExpense.splits.map(s => s.member_id),
        date: new Date(contextExpense.date),
        icon: undefined, // TODO: Add icon support to database
        lastModified: new Date(contextExpense.updated_at).getTime(),
        splits: contextExpense.splits.map(s => ({
            memberId: s.member_id,
            amountOwed: s.amount_owed
        })),
        expense_type: contextExpense.expense_type,
        created_at: contextExpense.created_at
    };
}

/**
 * Convert array of context Members to old format
 */
export function adaptMembers(contextMembers: ContextMember[]): OldMember[] {
    // Filter out any invalid members (null, undefined, or without name)
    return contextMembers
        .filter(m => m && m.name)
        .map(adaptMember);
}

/**
 * Convert array of context Expenses to old format
 */
export function adaptExpenses(contextExpenses: ExpenseWithSplits[]): OldExpense[] {
    // Filter out any invalid expenses
    return contextExpenses
        .filter(e => e && e.description && e.splits && e.splits.length > 0)
        .map(adaptExpense);
}
